<a href="https://colab.research.google.com/github/Krishna-Dhawangale/Resume-Screening-Machine-Learning-/blob/main/SVM_Resume_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ML_Data/AI_Resume_Screening.csv')
df.head(20)

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100)
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,NaN,AI Researcher,Hire,104895,8,100
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95
4,5,Julie Hill,"SQL, React, Java",4,PhD,NaN,Software Engineer,Hire,87441,9,100
5,6,Samantha Santos,"Cybersecurity, Networking, Linux, Ethical Hacking",10,B.Tech,Google ML,Cybersecurity Analyst,Hire,47957,5,100
6,7,Tony Smith,"Networking, Cybersecurity, Ethical Hacking",4,M.Tech,AWS Certified,Cybersecurity Analyst,Hire,66208,9,100
7,8,Anthony Harrison,"TensorFlow, Pytorch, NLP",3,M.Tech,AWS Certified,AI Researcher,Hire,103006,7,90
8,9,Nancy Jenkins,"Networking, Ethical Hacking",7,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,92270,3,100
9,10,Courtney Gibson,"Python, TensorFlow, Pytorch, NLP",0,M.Tech,AWS Certified,AI Researcher,Reject,60579,1,35
10,11,Laura French,"SQL, Java, C++",1,PhD,Deep Learning Specialization,Software Engineer,Hire,88945,7,70
11,12,Ralph Barrera,"Cybersecurity, Ethical Hacking, Networking",0,MBA,Google ML,Cybersecurity Analyst,Reject,62708,5,50
12,13,David Diaz,"Cybersecurity, Networking",0,M.Tech,Deep Learning Specialization,Cybersecurity Analyst,Hire,42077,9,65
13,14,Caitlin Myers,"SQL, C++, Java",4,B.Sc,Deep Learning Specialization,Software Engineer,Hire,50410,10,100
14,15,Tammy Pineda,"Pytorch, NLP",0,M.Tech,Deep Learning Specialization,AI Researcher,Reject,96555,5,45
15,16,Courtney Cook,"Cybersecurity, Networking",1,PhD,Google ML,Cybersecurity Analyst,Reject,51388,6,60
16,17,Megan Brown,"SQL, Python",10,PhD,NaN,Data Scientist,Hire,115364,2,100
17,18,Frances Davis MD,"Linux, Networking, Cybersecurity, Ethical Hacking",3,B.Tech,NaN,Cybersecurity Analyst,Hire,66379,6,80
18,19,Jonathon Pineda,"SQL, Python, Deep Learning",3,MBA,NaN,Data Scientist,Hire,112439,10,95
19,20,Jennifer Collins,"Machine Learning, SQL, Python",10,B.Tech,Deep Learning Specialization,Data Scientist,Hire,53167,9,100

In [15]:
df.shape

(1000, 11)

In [16]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Resume_ID               1000 non-null   int64
 1   Name                    1000 non-null   object
 2   Skills                  1000 non-null   object
 3   Experience (Years)      1000 non-null   int64
 4   Education               1000 non-null   object
 5   Certifications          726 non-null    object
 6   Job Role                1000 non-null   object
 7   Recruiter Decision      1000 non-null   object
 8   Salary Expectation ($)  1000 non-null   int64
 9   Projects Count          1000 non-null   int64
 10  AI Score (0-100)        1000 non-null   int64
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

Resume_ID                   0
Name                        0
Skills                      0
Experience (Years)          0
Education                   0
Certifications            274
Job Role                    0
Recruiter Decision          0
Salary Expectation ($)      0
Projects Count              0
AI Score (0-100)            0
dtype: int64

In [17]:
df.describe()

,Resume_ID,Experience (Years),Salary Expectation ($),Projects Count,AI Score (0-100)
count,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,500.500000,4.896000,79994.486000,5.13300,83.950000
std,288.819436,3.112695,23048.472549,3.23137,20.983036
min,1.000000,0.000000,40085.000000,0.00000,15.000000
25%,250.750000,2.000000,60415.750000,2.00000,70.000000
50%,500.500000,5.000000,79834.500000,5.00000,100.000000
75%,750.250000,8.000000,99583.250000,8.00000,100.000000
max,1000.000000,10.000000,119901.000000,10.00000,100.000000

In [24]:
df['Certifications'].fillna('No Certification', inplace=True)
df['Certifications'].isnull().sum()

np.int64(0)

In [25]:
df.isnull().sum()

Resume_ID                 0
Name                      0
Skills                    0
Experience (Years)        0
Education                 0
Certifications            0
Job Role                  0
Recruiter Decision        0
Salary Expectation ($)    0
Projects Count            0
AI Score (0-100)          0
Resume_Text               0
dtype: int64

In [26]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Resume_ID, Name, Skills, Experience (Years), Education, Certifications, Job Role, Recruiter Decision, Salary Expectation ($), Projects Count, AI Score (0-100), Resume_Text]
Index: []

In [27]:
print(df['Job Role'].unique())

['AI Researcher' 'Data Scientist' 'Cybersecurity Analyst'
 'Software Engineer']

In [28]:
print(df['Education'].unique())

['B.Sc' 'MBA' 'B.Tech' 'PhD' 'M.Tech']

In [29]:
df.head()

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100),Resume_Text
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,No Certification,AI Researcher,Hire,104895,8,100,"TensorFlow, NLP, Pytorch nan"
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100,"Deep Learning, Machine Learning, Python, SQL G..."
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70,"Ethical Hacking, Cybersecurity, Linux Deep Lea..."
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95,"Python, Pytorch, TensorFlow AWS Certified"
4,5,Julie Hill,"SQL, React, Java",4,PhD,No Certification,Software Engineer,Hire,87441,9,100,"SQL, React, Java nan"

In [30]:
df['Recruiter_Decision_Mapped'] = df['Recruiter Decision'].map({'Hire': 1, 'Reject': 0})
display(df.head())

,Resume_ID,Name,Skills,Experience (Years),Education,Certifications,Job Role,Recruiter Decision,Salary Expectation ($),Projects Count,AI Score (0-100),Resume_Text,Recruiter_Decision_Mapped
0,1,Ashley Ali,"TensorFlow, NLP, Pytorch",10,B.Sc,No Certification,AI Researcher,Hire,104895,8,100,"TensorFlow, NLP, Pytorch nan",1
1,2,Wesley Roman,"Deep Learning, Machine Learning, Python, SQL",10,MBA,Google ML,Data Scientist,Hire,113002,1,100,"Deep Learning, Machine Learning, Python, SQL G...",1
2,3,Corey Sanchez,"Ethical Hacking, Cybersecurity, Linux",1,MBA,Deep Learning Specialization,Cybersecurity Analyst,Hire,71766,7,70,"Ethical Hacking, Cybersecurity, Linux Deep Lea...",1
3,4,Elizabeth Carney,"Python, Pytorch, TensorFlow",7,B.Tech,AWS Certified,AI Researcher,Hire,46848,0,95,"Python, Pytorch, TensorFlow AWS Certified",1
4,5,Julie Hill,"SQL, React, Java",4,PhD,No Certification,Software Engineer,Hire,87441,9,100,"SQL, React, Java nan",1

In [31]:
X=df.iloc[:,:-1]
print(X)

     Resume_ID              Name  \
0            1        Ashley Ali
1            2      Wesley Roman
2            3     Corey Sanchez
3            4  Elizabeth Carney
4            5        Julie Hill
..         ...               ...
995        996   Brenda Williams
996        997     Colleen Hicks
997        998   Michelle Molina
998        999     Danielle Horn
999       1000      Chad Collins

                                                Skills  Experience (Years)  \
0                             TensorFlow, NLP, Pytorch                  10
1         Deep Learning, Machine Learning, Python, SQL                  10
2                Ethical Hacking, Cybersecurity, Linux                   1
3                          Python, Pytorch, TensorFlow                   7
4                                     SQL, React, Java                   4
..                                                 ...                 ...
995              Cybersecurity, Linux, Ethical Hacking                   0
996                    Deep Learning, Machine Learning                   0
997                                    TensorFlow, NLP                   0
998  Linux, Networking, Cybersecurity, Ethical Hacking                   8
999       SQL, Machine Learning, Python, Deep Learning                   7

    Education                Certifications               Job Role  \
0        B.Sc              No Certification          AI Researcher
1         MBA                     Google ML         Data Scientist
2         MBA  Deep Learning Specialization  Cybersecurity Analyst
3      B.Tech                 AWS Certified          AI Researcher
4         PhD              No Certification      Software Engineer
..        ...                           ...                    ...
995      B.Sc              No Certification  Cybersecurity Analyst
996       MBA  Deep Learning Specialization         Data Scientist
997    B.Tech                     Google ML          AI Researcher
998       PhD                 AWS Certified  Cybersecurity Analyst
999    M.Tech  Deep Learning Specialization         Data Scientist

    Recruiter Decision  Salary Expectation ($)  Projects Count  \
0                 Hire                  104895               8
1                 Hire                  113002               1
2                 Hire                   71766               7
3                 Hire                   46848               0
4                 Hire                   87441               9
..                 ...                     ...             ...
995             Reject                  114364               9
996             Reject                  103294               5
997               Hire                  113855               9
998               Hire                   83146              10
999               Hire                  119474               3

     AI Score (0-100)                                        Resume_Text
0                 100                       TensorFlow, NLP, Pytorch nan
1                 100  Deep Learning, Machine Learning, Python, SQL G...
2                  70  Ethical Hacking, Cybersecurity, Linux Deep Lea...
3                  95          Python, Pytorch, TensorFlow AWS Certified
4                 100                               SQL, React, Java nan
..                ...                                                ...
995                60          Cybersecurity, Linux, Ethical Hacking nan
996                45  Deep Learning, Machine Learning Deep Learning ...
997                65                          TensorFlow, NLP Google ML
998               100  Linux, Networking, Cybersecurity, Ethical Hack...
999               100  SQL, Machine Learning, Python, Deep Learning D...

[1000 rows x 12 columns]

In [32]:
Y=df.iloc[:,-1]
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
995    0
996    0
997    1
998    1
999    1
Name: Recruiter_Decision_Mapped, Length: 1000, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.7,test_size=0.3,random_state=42)

In [35]:
X_train.shape, X_test.shape

((700, 12), (300, 12))

In [42]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,Y_train)
Y_test=svc.predict(X_test)

In [44]:
acurracy=accuracy_score(Y_test,Y_test)
print(acurracy)

1.0

In [47]:
svc = SVC(C=100.0)
svc.fit(X_train, Y_train)
Y_pred = svc.predict(X_test)

In [48]:
accuracy_score(Y_test,Y_test)

1.0

In [49]:
liner_svc=SVC(kernel='linear',C=100.0)
liner_svc.fit(X_train,Y_train)
Y_test=liner_svc.predict(X_test)

In [50]:
accuracy_score(Y_test,Y_test)

1.0

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print('confusion Matrix')
cm=confusion_matrix(Y_test,Y_test)
print(cm)

confusion Matrix
[[ 61   0]
 [  0 239]]

In [53]:
# 1. Define numerical columns from the original DataFrame
numerical_cols = ['Experience (Years)', 'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)']
X_numerical = df[numerical_cols]
Y_true_labels = df['Recruiter_Decision_Mapped']

# 2. Re-split the data to get correct Y_test
from sklearn.model_selection import train_test_split
X_train_corrected, X_test_corrected, Y_train_corrected, Y_test_corrected = train_test_split(X_numerical, Y_true_labels, train_size=0.7, test_size=0.3, random_state=42)

# 3. Re-train the linear SVC model with corrected data
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

liner_svc_corrected = SVC(kernel='linear', C=100.0)
liner_svc_corrected.fit(X_train_corrected, Y_train_corrected)

# 4. Generate predictions using the re-trained model
Y_pred_corrected = liner_svc_corrected.predict(X_test_corrected)

# 5. Calculate and display evaluation metrics
print('Confusion Matrix:')
cm_corrected = confusion_matrix(Y_test_corrected, Y_pred_corrected)
print(cm_corrected)

print('\nClassification Report:')
report = classification_report(Y_test_corrected, Y_pred_corrected)
print(report)

accuracy_corrected = accuracy_score(Y_test_corrected, Y_pred_corrected)
print(f'\nAccuracy: {accuracy_corrected:.2f}')

Confusion Matrix:
[[ 60   4]
 [  1 235]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96        64
           1       0.98      1.00      0.99       236

    accuracy                           0.98       300
   macro avg       0.98      0.97      0.97       300
weighted avg       0.98      0.98      0.98       300


Accuracy: 0.98

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.8,test_size=0.2,random_state=42)

In [62]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()

In [65]:
numerical_cols = ['Experience (Years)', 'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)']
X_train_numerical = X_train[numerical_cols]
X_test_numerical = X_test[numerical_cols]

liner_svc=SVC(kernel='linear',C=100.0)
liner_svc.fit(X_train_numerical,Y_train)
Y_pred_test = liner_svc.predict(X_test_numerical)

In [66]:
accuracy_score(Y_test,Y_test)

1.0

In [67]:
# 1. Define numerical columns from the original DataFrame
numerical_cols = ['Experience (Years)', 'Salary Expectation ($)', 'Projects Count', 'AI Score (0-100)']
X_numerical = df[numerical_cols]
Y_true_labels = df['Recruiter_Decision_Mapped']

# 2. Re-split the data to get correct Y_test
from sklearn.model_selection import train_test_split
X_train_corrected, X_test_corrected, Y_train_corrected, Y_test_corrected = train_test_split(X_numerical, Y_true_labels, train_size=0.7, test_size=0.3, random_state=42)

# 3. Re-train the linear SVC model with corrected data
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

liner_svc_corrected = SVC(kernel='linear', C=100.0)
liner_svc_corrected.fit(X_train_corrected, Y_train_corrected)

# 4. Generate predictions using the re-trained model
Y_pred_corrected = liner_svc_corrected.predict(X_test_corrected)

# 5. Calculate and display evaluation metrics
print('Confusion Matrix:')
cm_corrected = confusion_matrix(Y_test_corrected, Y_pred_corrected)
print(cm_corrected)

print('\nClassification Report:')
report = classification_report(Y_test_corrected, Y_pred_corrected)
print(report)

accuracy_corrected = accuracy_score(Y_test_corrected, Y_pred_corrected)
print(f'\nAccuracy: {accuracy_corrected:.2f}')

Confusion Matrix:
[[ 60   4]
 [  1 235]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96        64
           1       0.98      1.00      0.99       236

    accuracy                           0.98       300
   macro avg       0.98      0.97      0.97       300
weighted avg       0.98      0.98      0.98       300


Accuracy: 0.98